version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Creating virtual environment..."
      - python3 -m venv myenv
      - echo "Activating virtual environment..."
      - source myenv/bin/activate
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the application..."
      - echo "Zipping the application for deployment..."
      - zip -r application.zip . -x "*.git*" "*.DS_Store*"

artifacts:
  files:
    - application.zip
